<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="lighting.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- Exclude cloned repositories from compilation -->
    <Compile Remove="raylib-cs\**" />
    <Compile Remove="Software-Rasterizer\**" />
    <EmbeddedResource Remove="raylib-cs\**" />
    <EmbeddedResource Remove="Software-Rasterizer\**" />
    <None Remove="raylib-cs\**" />
    <None Remove="Software-Rasterizer\**" />
  </ItemGroup>

</Project>
